#!/usr/bin/env node

// Some dependencies.

const app = require("../de_kelder.js")
const http = require("http")
const debug = require("debug")("de_kelder:server")

// The port.

const port = 3099
app.set("port", port)

// Create HTTP server.

const server = http.createServer(app)

// Listen to the provided port.

server.listen(port)
server.on("listening", onListening)

// Function for the listening event.

function onListening() {
    const addr = server.address()
    const bind = typeof addr == "string"
        ? "pipe " + addr
        : "port " + addr.port
    debug("Listening on " + bind)
}

process.on("SIGINT", () => {
    console.info("SIGINT signal received")

    server.close( (err) => {
        if (err) {
            console.error(err)
            process.exit(1)
        }
    })
})
